### ISSUE TITLE
Questions about the experiment in the paper

### ISSUE THREAD

**Issue by lingxiao-guo** [idiap/hypermixing#1]
Hello! I am impressed by your work on HyperMixer: An MLP-based Green AI Alternative to Transformers. It greatly reduces the computational complexity of transformers through a simple and elegant method, which greatly improves computational efficiency and is also very environmentally friendly! However, I have a question about the writing of the paper: did you not use a decoder when doing experiments with transformers? Or did you introduce decoders for both MLP mixer and HyperMixer? Thank you!

**Comment by florianmai** [comment]
Thank you for your interest!

Our paper only proposes a Transformer encoder alternative. It is not straight-forward to extend HyperMixing to decoding, but it is in principle possible. However, this requires a specialized CUDA implementation, which we are currently working on. We hope to release it by the end of the summer. Until then, if you would like to use HyperMixer in an encoder-decoder model, it's no problem to combine a HyperMixer encoder with a Transformer decoder. Moreover, studies have shown that in general it is more efficient to use many encoder layers and few decoder layers, so it's possible to have most of your model be HyperMixer.
